// Multi-language support
// Languages: English, Gujarati, Hindi

const translations = {
  en: {
    nav_dashboard: "Keka",
    nav_workspace: "Workspace",
    nav_settings: "Settings",
    nav_theme: "Theme",

    page_title: "Today's Attendance",
    page_subtitle: "Track your hours and plan your exit",

    status_no_data: "No data yet. Connect to Keka.",
    status_accomplished: "Day complete",
    status_grinding: "Still working",
    status_ticking: "Clock is running",

    label_first_in: "First IN",
    label_last_out: "Last OUT",
    label_gross_hours: "Gross Hours",
    label_effective_hours: "Effective Hours",
    label_break_time: "Break Time",
    label_target_exit: "Target Exit",
    label_workspace_total: "Workspace Timer (Total logged)",

    countdown_title: "Time Remaining",
    countdown_subtitle: "Until your target exit time",
    countdown_done: "Done",
    countdown_overtime: "Overtime",

    punch_card_title: "Today's Punch Card",

    sync_title: "Keka Sync",
    sync_text: "Attendance syncs automatically from Keka",
    sync_button: "Connect to Keka",
    sync_syncing: "Syncing attendance data...",
    sync_success: "Synced. Last updated:",
    sync_error: "Sync failed. Please try again.",

    footer_made_by: "Crafted by",
    footer_author: "Neel Patel",

    settings_title: "Settings",
    settings_subtitle: "Manage your preferences",

    tab_control_center: "Control Center",
    tab_general: "General",

    token_title: "Keka Connection",
    token_checking: "Checking...",
    token_connected: "Connected",
    token_disconnected: "Not Connected",
    token_status_ok: "Keka connection is active.",
    token_status_none: "No connection yet. Connect from the Keka tab.",

    notifications_title: "Reminders",
    notifications_desc: "Set reminders to stay on track",

    about_title: "About",
    about_version: "Version:",
    about_version_text: "1.2.0",
    about_purpose: "Purpose:",
    about_purpose_text: "Workplace hours and EOD assistant",
    about_features: "Features:",
    about_features_text:
      "Keka sync, Teams EOD, Smart suggestions, Notifications",
    about_status: "Status:",
    about_status_text: "Active",

    btn_test_notification: "Test Alert",
    btn_save_settings: "Save Preferences",

    shift_title: "Shift Information",
    shift_loading: "Loading shift data...",
    shift_error: "Unable to load shift data",
    shift_retry: "Try Again",
    shift_name: "Shift Name",
    shift_start: "Shift Start",
    shift_end: "Shift End",
    shift_duration: "Duration",

    preferences_title: "App Preferences",
    pref_language: "Language / ભાષા / भाषा",
    pref_dark_mode: "Dark Mode",
    pref_notifications: "Enable Alerts",
    pref_auto_sync: "Auto-sync on Open",
    pref_funny_text: "Funny Text Mode",

    ws_sender_auto: "Sender ID: auto-detected from Teams",
    ws_fetch_user_id: "Fetch User ID",
    ws_fetching_user_id: "Fetching...",
    ws_user_id_fetched: "User ID detected successfully",
    ws_user_id_fetch_failed: "Could not detect User ID automatically",
    ws_user_id_required:
      "Teams User ID required. Open Teams or fetch it first.",
    ws_from_id_manual_hint:
      "Auto-detect failed. Enter your Teams User ID manually.",

    // Funny mode labels (UI only)
    nav_dashboard_funny: "Keka",
    nav_workspace_funny: "Workspace",
    nav_settings_funny: "Settings",
    nav_theme_funny: "Theme",
    page_title_funny: "Time's Ticking, Boss!",
    page_subtitle_funny: "Your daily grind tracker",
    status_no_data_funny: "No data yet. Connect to Keka!",
    status_accomplished_funny: "Mission Accomplished!",
    status_grinding_funny: "Still Grinding...",
    status_ticking_funny: "Clock is Ticking!",
    label_first_in_funny: "First IN",
    label_last_out_funny: "Last OUT",
    label_gross_hours_funny: "Gross Hours",
    label_effective_hours_funny: "Effective Hours",
    label_break_time_funny: "Break Time",
    label_target_exit_funny: "Target Exit",
    countdown_title_funny: "Freedom Countdown",
    countdown_subtitle_funny: "Time until you can escape!",
    countdown_done_funny: "Done!",
    countdown_overtime_funny: "Overtime!",
    punch_card_title_funny: "Today's Punch Card",
    sync_title_funny: "Auto-Magic Sync",
    sync_text_funny: "Your attendance syncs automagically from Keka!",
    sync_button_funny: "Connect to Keka Universe",
    sync_syncing_funny: "Syncing your attendance data...",
    sync_success_funny: "Synced! Last updated:",
    sync_error_funny: "Sync failed. Please try again.",
    footer_made_by_funny: "Crafted by",
    settings_title_funny: "Settings",
    settings_subtitle_funny: "Manage your preferences",
    tab_control_center_funny: "Control Center",
    tab_general_funny: "General",
    token_title_funny: "Secret Sauce Status",
    token_status_ok_funny:
      "You're all set! Your magical connection is active.",
    token_status_none_funny:
      "No connection yet. Hit Connect on the Keka tab!",
    notifications_title_funny: "Nudge Me When...",
    notifications_desc_funny: "Set up friendly reminders to keep you on track!",
    about_title_funny: "About This Wizardry",
    about_purpose_text_funny: "Making work hours less boring!",
    about_features_text_funny:
      "Auto-sync, Smart notifications, Dark mode magic",
    about_status_text_funny: "Working harder than you!",
    preferences_title_funny: "App Preferences",
    pref_funny_text_funny: "Funny Text Mode",
    ws_title_funny: "Workspace EOD HQ",
    ws_subtitle_funny: "Ping Teams when your timer stops",
    ws_connection_title_funny: "Connection Status",
    ws_config_title_funny: "Teams Setup",
    ws_smart_title_funny: "Smart Suggestion",
    ws_quick_title_funny: "Quick EOD",
    ws_prefs_title_funny: "EOD Preferences",
    ws_sender_auto_funny: "Sender ID: auto-detected (magic!)",

    ws_title: "Workspace & EOD",
    ws_subtitle: "Teams updates when your timer stops",
    ws_connection_title: "Connection Status",
    ws_configured: "Configured",
    ws_not_configured: "Not Configured",
    ws_configured_hint: "Teams and Workspace are ready for EOD messages.",
    ws_not_configured_hint: "Complete Teams configuration below to enable EOD.",
    ws_token_none: "No Teams token",
    ws_token_none_hint: "Open Teams to capture your token.",
    ws_token_expired: "Token expired",
    ws_token_expired_hint: "Open Teams to refresh your token.",
    ws_token_valid: "Token valid",
    ws_token_expires: "Expires in {h}h {m}m",
    ws_token_expires_soon: "Expires in {m} minutes",
    ws_open_teams: "Open Teams",
    ws_open_workspace: "Open Workspace",
    ws_refresh_token: "Refresh Token",
    ws_config_title: "Teams Configuration",
    ws_display_name: "Display Name",
    ws_from_id: "Teams User ID",
    ws_group: "Teams Group",
    ws_groups_loading: "Loading groups...",
    ws_groups_error: "Could not load groups",
    ws_groups_empty: "No groups found",
    ws_save_config: "Save Configuration",
    ws_save_success: "Configuration saved",
    ws_save_error: "Please fill all required fields",
    ws_smart_title: "Smart Suggestion",
    ws_suggested: "Suggested message",
    ws_suggestion_from_keka: "Based on your Keka attendance today",
    ws_suggestion_no_keka: "No Keka data — using default suggestion",
    ws_send_suggested: "Send Suggested Message",
    ws_quick_title: "Quick EOD",
    ws_custom_placeholder: "Custom message...",
    ws_send: "Send",
    ws_sending: "Sending...",
    ws_sent_success: "Message sent to Teams",
    ws_sent_error: "Failed to send message",
    ws_prefs_title: "EOD Preferences",
    ws_auto_prompt: "Auto-prompt on timer stop",
    ws_presets_desc: "Edit your preset messages:",
    ws_add_preset: "Add Preset",
    ws_save_presets: "Save Presets",
    ws_presets_saved: "Presets saved",
    ws_presets_empty: "Add at least one preset message",
    ws_preset_placeholder: "New preset message",

    ws_timesheet_title: "Today's Timesheet",
    ws_timesheet_total: "Total logged",
    ws_timesheet_timer: "Timer status",
    ws_timesheet_running: "Running",
    ws_timesheet_stopped: "Stopped",
    ws_timesheet_active_task: "Active task",
    ws_timesheet_last_entry: "Last entry",
    ws_timesheet_sync: "Last synced",
    ws_timesheet_refresh: "Refresh",
    ws_timesheet_syncing: "Syncing timesheet...",
    ws_timesheet_no_session: "Open Workspace to connect",
    ws_timesheet_no_session_hint: "Log in to Workspace to sync your timesheet.",
    ws_timesheet_none: "No entries today",
    ws_timesheet_elapsed: "Session elapsed",
    ws_tasks_title: "Your tasks",
    ws_task_start: "Start",
    ws_task_starting: "Starting...",
    ws_timer_already_running: "A timer is already running",
    ws_timer_started: "Timer started",
    ws_timer_start_failed: "Failed to start timer",
    ws_tasks_empty: "No tasks found",
    ws_timer_alerts: "Workspace timer alerts",
    ws_timer_alerts_desc: "Weekday reminders to start/stop timer (10am–9pm; no start alerts 1–2pm)",
    ws_alert_interval: "Alert check interval",
    ws_alert_interval_1: "Every 1 minute",
    ws_alert_interval_5: "Every 5 minutes",
    ws_alert_interval_15: "Every 15 minutes",
    ws_alert_interval_30: "Every 30 minutes",

    alert_dismiss: "Dismiss",
    alert_open_workspace: "Open Workspace",
    alert_open_keka: "Open Keka",
    alert_reminder_label: "Reminder",
    alert_exit_title: "Exit Reminder",
    alert_exit_message_early: "10 minutes until 7 PM! Almost freedom time!",
    alert_exit_message: "10 minutes until your exit time!",
    alert_effective_title: "8 Hours Complete",
    alert_target_exit_title: "Target Exit",
    alert_test_title: "Test Alert",
    alert_test_message: "Your alerts are working correctly.",
    alert_ws_start_title: "Start Workspace Timer",
    alert_ws_start_message: "You are punched in on Keka but no workspace timer is running.",
    alert_ws_stop_title: "Stop Workspace Timer",
    alert_ws_stop_message: "You have logged 8h 5m+. Consider stopping your timer and sending EOD.",
    eod_modal_title: "Send update to Teams",
    eod_modal_label: "EOD",
    eod_modal_instruction: "Select a message to send to your group:",
    eod_custom_toggle: "Write a Custom Message...",
    eod_send_custom: "Send Custom Message",
    eod_custom_placeholder: "Type your message here...",
    eod_suggested_prefix: "Suggested:",
  },

  gu: {
    nav_dashboard: "કેકા",
    nav_workspace: "વર્કસ્પેસ",
    nav_settings: "સેટિંગ્સ",
    nav_theme: "થીમ",

    page_title: "આજનું એટેન્ડન્સ",
    page_subtitle: "તમારા કલાકો ટ્રેક કરો અને બહાર નીકળવાનો સમય યોજો",

    status_no_data: "હજુ ડેટા નથી. કેકા સાથે કનેક્ટ કરો.",
    status_accomplished: "દિવસ પૂર્ણ",
    status_grinding: "હજુ કામ ચાલુ છે",
    status_ticking: "ઘડિયાળ ચાલુ છે",

    label_first_in: "પહેલું IN",
    label_last_out: "છેલ્લું OUT",
    label_gross_hours: "કુલ કલાકો",
    label_effective_hours: "અસરકારક કલાકો",
    label_break_time: "બ્રેક ટાઈમ",
    label_target_exit: "લક્ષ્ય બહાર નીકળવાનો સમય",
    label_workspace_total: "વર્કસ્પેસ ટાઇમર (કુલ લોગ)",

    countdown_title: "બાકી સમય",
    countdown_subtitle: "તમારા લક્ષ્ય બહાર નીકળવાના સમય સુધી",
    countdown_done: "થઈ ગયું",
    countdown_overtime: "ઓવરટાઈમ",

    punch_card_title: "આજનું પંચ કાર્ડ",

    sync_title: "કેકા સિંક",
    sync_text: "એટેન્ડન્સ કેકામાંથી ઓટોમેટિક સિંક થાય છે",
    sync_button: "કેકા સાથે કનેક્ટ કરો",
    sync_syncing: "એટેન્ડન્સ સિંક થઈ રહ્યું છે...",
    sync_success: "સિંક થયું. છેલ્લું અપડેટ:",
    sync_error: "સિંક નિષ્ફળ. ફરી પ્રયાસ કરો.",

    footer_made_by: "બનાવ્યું",
    footer_author: "નીલ પટેલ",

    settings_title: "સેટિંગ્સ",
    settings_subtitle: "તમારી પસંદગીઓ મેનેજ કરો",

    tab_control_center: "કંટ્રોલ સેન્ટર",
    tab_general: "સામાન્ય",

    token_title: "કેકા કનેક્શન",
    token_checking: "ચેક કરી રહ્યા છીએ...",
    token_connected: "કનેક્ટેડ",
    token_disconnected: "કનેક્ટેડ નથી",
    token_status_ok: "કેકા કનેક્શન સક્રિય છે.",
    token_status_none: "હજુ કનેક્શન નથી. કેકા ટેબથી કનેક્ટ કરો.",

    notifications_title: "રિમાઇન્ડર",
    notifications_desc: "ટ્રેક પર રહેવા રિમાઇન્ડર સેટ કરો",

    about_title: "વિશે",
    about_version: "વર્ઝન:",
    about_version_text: "1.2.0",
    about_purpose: "હેતુ:",
    about_purpose_text: "કાર્યસ્થળ કલાકો અને EOD સહાયક",
    about_features: "ફીચર્સ:",
    about_features_text: "કેકા સિંક, ટીમ્સ EOD, સ્માર્ટ સૂચનો, નોટિફિકેશન્સ",
    about_status: "સ્ટેટસ:",
    about_status_text: "સક્રિય",

    btn_test_notification: "ટેસ્ટ અલર્ટ",
    btn_save_settings: "પસંદગીઓ સેવ કરો",

    shift_title: "શિફ્ટ માહિતી",
    shift_loading: "શિફ્ટ ડેટા લોડ થઈ રહ્યો છે...",
    shift_error: "શિફ્ટ ડેટા લોડ કરવામાં અસમર્થ",
    shift_retry: "ફરી પ્રયાસ કરો",
    shift_name: "શિફ્ટનું નામ",
    shift_start: "શિફ્ટ શરૂઆત",
    shift_end: "શિફ્ટ અંત",
    shift_duration: "અવધિ",

    preferences_title: "એપ પસંદગીઓ",
    pref_language: "ભાષા / Language / भाषा",
    pref_dark_mode: "ડાર્ક મોડ",
    pref_notifications: "અલર્ટ સક્ષમ કરો",
    pref_auto_sync: "ખોલતી વખતે ઓટો-સિંક",
    pref_funny_text: "ફની ટેક્સ્ટ મોડ",

    ws_sender_auto: "સેન્ડર ID: ટીમ્સમાંથી ઓટો-ડિટેક્ટ",
    ws_fetch_user_id: "યુઝર ID લાવો",
    ws_fetching_user_id: "લાવી રહ્યા છીએ...",
    ws_user_id_fetched: "યુઝર ID સફળતાપૂર્વક મળ્યું",
    ws_user_id_fetch_failed: "યુઝર ID ઓટો-ડિટેક્ટ થયું નહીં",
    ws_user_id_required: "ટીમ્સ યુઝર ID જરૂરી છે. ટીમ્સ ખોલો અથવા પહેલા લાવો.",
    ws_from_id_manual_hint: "ઓટો-ડિટેક્ટ નિષ્ફળ. મેન્યુઅલી યુઝર ID દાખલ કરો.",

    nav_dashboard_funny: "કેકા",
    page_title_funny: "સમય ભાગી રહ્યો છે, બોસ!",
    page_subtitle_funny: "તમારું રોજનું કામ ટ્રેક કરો",
    countdown_title_funny: "છૂટકારાની ગણતરી",
    sync_title_funny: "ઓટો-મેજિક સિંક",
    token_title_funny: "સિક્રેટ સોસ સ્ટેટસ",
    settings_title_funny: "સેટિંગ્સ",
    ws_title_funny: "વર્કસ્પેસ EOD HQ",
    pref_funny_text_funny: "ફની ટેક્સ્ટ મોડ",

    ws_title: "વર્કસ્પેસ અને EOD",
    ws_subtitle: "ટાઈમર બંધ થાય ત્યારે ટીમ્સ અપડેટ",
    ws_connection_title: "કનેક્શન સ્ટેટસ",
    ws_configured: "કોન્ફિગર થયું",
    ws_not_configured: "કોન્ફિગર નથી",
    ws_configured_hint: "ટીમ્સ અને વર્કસ્પેસ EOD માટે તૈયાર છે.",
    ws_not_configured_hint: "EOD સક્ષમ કરવા નીચે ટીમ્સ કોન્ફિગરેશન પૂર્ણ કરો.",
    ws_token_none: "ટીમ્સ ટોકન નથી",
    ws_token_none_hint: "ટોકન કેપ્ચર કરવા ટીમ્સ ખોલો.",
    ws_token_expired: "ટોકન એક્સપાયર",
    ws_token_expired_hint: "ટોકન રિફ્રેશ કરવા ટીમ્સ ખોલો.",
    ws_token_valid: "ટોકન માન્ય",
    ws_token_expires: "{h} કલાક {m} મિનિટમાં એક્સપાયર",
    ws_token_expires_soon: "{m} મિનિટમાં એક્સપાયર",
    ws_open_teams: "ટીમ્સ ખોલો",
    ws_open_workspace: "વર્કસ્પેસ ખોલો",
    ws_refresh_token: "ટોકન રિફ્રેશ",
    ws_config_title: "ટીમ્સ કોન્ફિગરેશન",
    ws_display_name: "ડિસ્પ્લે નામ",
    ws_from_id: "ટીમ્સ યુઝર ID",
    ws_group: "ટીમ્સ ગ્રુપ",
    ws_groups_loading: "ગ્રુપ લોડ થઈ રહ્યા છે...",
    ws_groups_error: "ગ્રુપ લોડ થયા નહીં",
    ws_groups_empty: "કોઈ ગ્રુપ મળ્યું નહીં",
    ws_save_config: "કોન્ફિગરેશન સેવ કરો",
    ws_save_success: "કોન્ફિગરેશન સેવ થયું",
    ws_save_error: "બધા જરૂરી ફીલ્ડ ભરો",
    ws_smart_title: "સ્માર્ટ સૂચન",
    ws_suggested: "સૂચવેલ સંદેશ",
    ws_suggestion_from_keka: "આજના કેકા એટેન્ડન્સ પર આધારિત",
    ws_suggestion_no_keka: "કેકા ડેટા નથી — ડિફોલ્ટ સૂચન",
    ws_send_suggested: "સૂચવેલ સંદેશ મોકલો",
    ws_quick_title: "ઝડપી EOD",
    ws_custom_placeholder: "કસ્ટમ સંદેશ...",
    ws_send: "મોકલો",
    ws_sending: "મોકલી રહ્યા છીએ...",
    ws_sent_success: "ટીમ્સ પર સંદેશ મોકલ્યો",
    ws_sent_error: "સંદેશ મોકલવામાં નિષ્ફળ",
    ws_prefs_title: "EOD પસંદગીઓ",
    ws_auto_prompt: "ટાઈમર બંધ પર ઓટો-પ્રોમ્પ્ટ",
    ws_presets_desc: "પ્રીસેટ સંદેશો સંપાદિત કરો:",
    ws_add_preset: "પ્રીસેટ ઉમેરો",
    ws_save_presets: "પ્રીસેટ સેવ કરો",
    ws_presets_saved: "પ્રીસેટ સેવ થયા",
    ws_presets_empty: "ઓછામાં ઓછો એક પ્રીસેટ ઉમેરો",
    ws_preset_placeholder: "નવો પ્રીસેટ સંદેશ",

    ws_timesheet_title: "આજનું ટાઈમશીટ",
    ws_timesheet_total: "કુલ લોગ થયેલ",
    ws_timesheet_timer: "ટાઈમર સ્ટેટસ",
    ws_timesheet_running: "ચાલુ છે",
    ws_timesheet_stopped: "બંધ છે",
    ws_timesheet_active_task: "સક્રિય ટાસ્ક",
    ws_timesheet_last_entry: "છેલ્લી એન્ટ્રી",
    ws_timesheet_sync: "છેલ્લું સિંક",
    ws_timesheet_refresh: "રિફ્રેશ",
    ws_timesheet_syncing: "ટાઈમશીટ સિંક થઈ રહ્યું છે...",
    ws_timesheet_no_session: "કનેક્ટ કરવા વર્કસ્પેસ ખોલો",
    ws_timesheet_no_session_hint: "ટાઈમશીટ સિંક કરવા વર્કસ્પેસમાં લૉગ ઇન કરો.",
    ws_timesheet_none: "આજે કોઈ એન્ટ્રી નથી",
    ws_timesheet_elapsed: "સેશન સમય",
    ws_tasks_title: "તમારા ટાસ્ક",
    ws_task_start: "શરૂ કરો",
    ws_task_starting: "શરૂ થઈ રહ્યું છે...",
    ws_timer_already_running: "ટાઈમર પહેલેથી ચાલુ છે",
    ws_timer_started: "ટાઈમર શરૂ થયો",
    ws_timer_start_failed: "ટાઈમર શરૂ કરવામાં નિષ્ફળ",
    ws_tasks_empty: "કોઈ ટાસ્ક મળ્યું નહીં",
    ws_timer_alerts: "વર્કસ્પેસ ટાઈમર અલર્ટ",
    ws_timer_alerts_desc: "ટાઈમર શરૂ/બંધ રિમાઇન્ડર (સોમ–શુક્ર, 10–9; 1–2 વાગ્યે શરૂ અલર્ટ નહીં)",
    ws_alert_interval: "અલર્ટ ચેક અંતરાલ",
    ws_alert_interval_1: "દર 1 મિનિટ",
    ws_alert_interval_5: "દર 5 મિનિટ",
    ws_alert_interval_15: "દર 15 મિનિટ",
    ws_alert_interval_30: "દર 30 મિનિટ",

    alert_dismiss: "બંધ કરો",
    alert_open_workspace: "વર્કસ્પેસ ખોલો",
    alert_open_keka: "કેકા ખોલો",
    alert_reminder_label: "રિમાઇન્ડર",
    alert_exit_title: "બહાર નીકળવાનો રિમાઇન્ડર",
    alert_exit_message_early: "7 વાગ્યા સુધી 10 મિનિટ! લગભગ છૂટી ગયું!",
    alert_exit_message: "તમારા લક્ષ્ય સમય સુધી 10 મિનિટ!",
    alert_effective_title: "8 કલાક પૂર્ણ",
    alert_target_exit_title: "લક્ષ્ય બહાર નીકળવું",
    alert_test_title: "ટેસ્ટ અલર્ટ",
    alert_test_message: "તમારા અલર્ટ યોગ્ય રીતે કામ કરે છે.",
    alert_ws_start_title: "વર્કસ્પેસ ટાઈમર શરૂ કરો",
    alert_ws_start_message: "તમે કેકામાં IN છો પણ વર્કસ્પેસ ટાઈમર ચાલુ નથી.",
    alert_ws_stop_title: "વર્કસ્પેસ ટાઈમર બંધ કરો",
    alert_ws_stop_message: "તમે 8 કલાક 5 મિનિટ+ લોગ કર્યું છે. ટાઈમર બંધ કરો અને EOD મોકલો.",
    eod_modal_title: "ટીમ્સ પર અપડેટ મોકલો",
    eod_modal_label: "EOD",
    eod_modal_instruction: "તમારા ગ્રુપને મોકલવા માટે સંદેશ પસંદ કરો:",
    eod_custom_toggle: "કસ્ટમ સંદેશ લખો...",
    eod_send_custom: "કસ્ટમ સંદેશ મોકલો",
    eod_custom_placeholder: "તમારો સંદેશ અહીં લખો...",
    eod_suggested_prefix: "સૂચવેલ:",
  },

  hi: {
    nav_dashboard: "केका",
    nav_workspace: "वर्कस्पेस",
    nav_settings: "सेटिंग्स",
    nav_theme: "थीम",

    page_title: "आज की उपस्थिति",
    page_subtitle: "अपने घंटे ट्रैक करें और निकलने का समय प्लान करें",

    status_no_data: "अभी डेटा नहीं है। केका से कनेक्ट करें।",
    status_accomplished: "दिन पूरा",
    status_grinding: "अभी काम चल रहा है",
    status_ticking: "घड़ी चल रही है",

    label_first_in: "पहला IN",
    label_last_out: "आखिरी OUT",
    label_gross_hours: "कुल घंटे",
    label_effective_hours: "प्रभावी घंटे",
    label_break_time: "ब्रेक टाइम",
    label_target_exit: "लक्ष्य निकास समय",
    label_workspace_total: "वर्कस्पेस टाइमर (कुल लॉग)",

    countdown_title: "शेष समय",
    countdown_subtitle: "आपके लक्ष्य निकास समय तक",
    countdown_done: "हो गया",
    countdown_overtime: "ओवरटाइम",

    punch_card_title: "आज का पंच कार्ड",

    sync_title: "केका सिंक",
    sync_text: "उपस्थिति केका से स्वचालित सिंक होती है",
    sync_button: "केका से कनेक्ट करें",
    sync_syncing: "उपस्थिति सिंक हो रही है...",
    sync_success: "सिंक हो गया। आखिरी अपडेट:",
    sync_error: "सिंक विफल। फिर से प्रयास करें।",

    footer_made_by: "बनाया",
    footer_author: "नील पटेल",

    settings_title: "सेटिंग्स",
    settings_subtitle: "अपनी पसंद मैनेज करें",

    tab_control_center: "कंट्रोल सेंटर",
    tab_general: "सामान्य",

    token_title: "केका कनेक्शन",
    token_checking: "चेक कर रहे हैं...",
    token_connected: "कनेक्टेड",
    token_disconnected: "कनेक्टेड नहीं",
    token_status_ok: "केका कनेक्शन सक्रिय है।",
    token_status_none: "अभी कनेक्शन नहीं है। केका टैब से कनेक्ट करें।",

    notifications_title: "रिमाइंडर",
    notifications_desc: "ट्रैक पर रहने के लिए रिमाइंडर सेट करें",

    about_title: "के बारे में",
    about_version: "वर्जन:",
    about_version_text: "1.2.0",
    about_purpose: "उद्देश्य:",
    about_purpose_text: "कार्यस्थल घंटे और EOD सहायक",
    about_features: "फीचर्स:",
    about_features_text: "केका सिंक, टीम्स EOD, स्मार्ट सुझाव, नोटिफिकेशन",
    about_status: "स्टेटस:",
    about_status_text: "सक्रिय",

    btn_test_notification: "टेस्ट अलर्ट",
    btn_save_settings: "पसंद सेव करें",

    shift_title: "शिफ्ट जानकारी",
    shift_loading: "शिफ्ट डेटा लोड हो रहा है...",
    shift_error: "शिफ्ट डेटा लोड करने में असमर्थ",
    shift_retry: "फिर से प्रयास करें",
    shift_name: "शिफ्ट का नाम",
    shift_start: "शिफ्ट शुरुआत",
    shift_end: "शिफ्ट अंत",
    shift_duration: "अवधि",

    preferences_title: "ऐप पसंद",
    pref_language: "भाषा / Language / ભાષા",
    pref_dark_mode: "डार्क मोड",
    pref_notifications: "अलर्ट सक्षम करें",
    pref_auto_sync: "खोलते समय ऑटो-सिंक",
    pref_funny_text: "फनी टेक्स्ट मोड",

    ws_sender_auto: "सेंडर ID: Teams से ऑटो-डिटेक्ट",
    ws_fetch_user_id: "यूजर ID लाएं",
    ws_fetching_user_id: "लोड हो रहा है...",
    ws_user_id_fetched: "यूजर ID सफलतापूर्वक मिला",
    ws_user_id_fetch_failed: "यूजर ID ऑटो-डिटेक्ट नहीं हो सका",
    ws_user_id_required: "Teams यूजर ID जरूरी है। Teams खोलें या पहले लाएं।",
    ws_from_id_manual_hint: "ऑटो-डिटेक्ट विफल। मैन्युअल यूजर ID दर्ज करें।",

    nav_dashboard_funny: "केका",
    page_title_funny: "समय भाग रहा है, बॉस!",
    page_subtitle_funny: "आपका दैनिक काम ट्रैकर",
    countdown_title_funny: "छुट्टी की गिनती",
    sync_title_funny: "ऑटो-मैजिक सिंक",
    token_title_funny: "सीक्रेट सॉस स्टेटस",
    settings_title_funny: "सेटिंग्स",
    ws_title_funny: "वर्कस्पेस EOD HQ",
    pref_funny_text_funny: "फनी टेक्स्ट मोड",

    ws_title: "वर्कस्पेस और EOD",
    ws_subtitle: "टाइमर बंद होने पर टीम्स अपडेट",
    ws_connection_title: "कनेक्शन स्टेटस",
    ws_configured: "कॉन्फ़िगर",
    ws_not_configured: "कॉन्फ़िगर नहीं",
    ws_configured_hint: "टीम्स और वर्कस्पेस EOD के लिए तैयार हैं।",
    ws_not_configured_hint:
      "EOD सक्षम करने के लिए नीचे टीम्स कॉन्फ़िगरेशन पूरा करें।",
    ws_token_none: "टीम्स टोकन नहीं",
    ws_token_none_hint: "टोकन कैप्चर करने के लिए टीम्स खोलें।",
    ws_token_expired: "टोकन समाप्त",
    ws_token_expired_hint: "टोकन रिफ्रेश करने के लिए टीम्स खोलें।",
    ws_token_valid: "टोकन मान्य",
    ws_token_expires: "{h} घंटे {m} मिनट में समाप्त",
    ws_token_expires_soon: "{m} मिनट में समाप्त",
    ws_open_teams: "टीम्स खोलें",
    ws_open_workspace: "वर्कस्पेस खोलें",
    ws_refresh_token: "टोकन रिफ्रेश",
    ws_config_title: "टीम्स कॉन्फ़िगरेशन",
    ws_display_name: "डिस्प्ले नाम",
    ws_from_id: "टीम्स यूजर ID",
    ws_group: "टीम्स ग्रुप",
    ws_groups_loading: "ग्रुप लोड हो रहे हैं...",
    ws_groups_error: "ग्रुप लोड नहीं हो सके",
    ws_groups_empty: "कोई ग्रुप नहीं मिला",
    ws_save_config: "कॉन्फ़िगरेशन सेव करें",
    ws_save_success: "कॉन्फ़िगरेशन सेव हो गया",
    ws_save_error: "सभी आवश्यक फ़ील्ड भरें",
    ws_smart_title: "स्मार्ट सुझाव",
    ws_suggested: "सुझाया गया संदेश",
    ws_suggestion_from_keka: "आज की केका उपस्थिति के आधार पर",
    ws_suggestion_no_keka: "केका डेटा नहीं — डिफ़ॉल्ट सुझाव",
    ws_send_suggested: "सुझाया संदेश भेजें",
    ws_quick_title: "त्वरित EOD",
    ws_custom_placeholder: "कस्टम संदेश...",
    ws_send: "भेजें",
    ws_sending: "भेजा जा रहा है...",
    ws_sent_success: "टीम्स पर संदेश भेजा गया",
    ws_sent_error: "संदेश भेजने में विफल",
    ws_prefs_title: "EOD पसंद",
    ws_auto_prompt: "टाइमर बंद पर ऑटो-प्रॉम्प्ट",
    ws_presets_desc: "प्रीसेट संदेश संपादित करें:",
    ws_add_preset: "प्रीसेट जोड़ें",
    ws_save_presets: "प्रीसेट सेव करें",
    ws_presets_saved: "प्रीसेट सेव हो गए",
    ws_presets_empty: "कम से कम एक प्रीसेट जोड़ें",
    ws_preset_placeholder: "नया प्रीसेट संदेश",

    ws_timesheet_title: "आज का टाइमशीट",
    ws_timesheet_total: "कुल लॉग",
    ws_timesheet_timer: "टाइमर स्थिति",
    ws_timesheet_running: "चल रहा है",
    ws_timesheet_stopped: "बंद",
    ws_timesheet_active_task: "सक्रिय कार्य",
    ws_timesheet_last_entry: "आखिरी एंट्री",
    ws_timesheet_sync: "आखिरी सिंक",
    ws_timesheet_refresh: "रिफ्रेश",
    ws_timesheet_syncing: "टाइमशीट सिंक हो रहा है...",
    ws_timesheet_no_session: "कनेक्ट करने के लिए वर्कस्पेस खोलें",
    ws_timesheet_no_session_hint: "टाइमशीट सिंक के लिए वर्कस्पेस में लॉग इन करें।",
    ws_timesheet_none: "आज कोई एंट्री नहीं",
    ws_timesheet_elapsed: "सत्र समय",
    ws_tasks_title: "आपके कार्य",
    ws_task_start: "शुरू करें",
    ws_task_starting: "शुरू हो रहा है...",
    ws_timer_already_running: "टाइमर पहले से चल रहा है",
    ws_timer_started: "टाइमर शुरू हो गया",
    ws_timer_start_failed: "टाइमर शुरू करने में विफल",
    ws_tasks_empty: "कोई कार्य नहीं मिला",
    ws_timer_alerts: "वर्कस्पेस टाइमर अलर्ट",
    ws_timer_alerts_desc: "टाइमर शुरू/बंद रिमाइंडर (सोम–शुक्र, 10–9; 1–2 बजे शुरू अलर्ट नहीं)",
    ws_alert_interval: "अलर्ट जांच अंतराल",
    ws_alert_interval_1: "हर 1 मिनट",
    ws_alert_interval_5: "हर 5 मिनट",
    ws_alert_interval_15: "हर 15 मिनट",
    ws_alert_interval_30: "हर 30 मिनट",

    alert_dismiss: "बंद करें",
    alert_open_workspace: "वर्कस्पेस खोलें",
    alert_open_keka: "केका खोलें",
    alert_reminder_label: "रिमाइंडर",
    alert_exit_title: "निकास रिमाइंडर",
    alert_exit_message_early: "7 बजे तक 10 मिनट! लगभग छुट्टी!",
    alert_exit_message: "आपके लक्ष्य समय तक 10 मिनट!",
    alert_effective_title: "8 घंटे पूरे",
    alert_target_exit_title: "लक्ष्य निकास",
    alert_test_title: "टेस्ट अलर्ट",
    alert_test_message: "आपके अलर्ट सही काम कर रहे हैं।",
    alert_ws_start_title: "वर्कस्पेस टाइमर शुरू करें",
    alert_ws_start_message: "आप Keka में IN हैं लेकिन वर्कस्पेस टाइमर नहीं चल रहा।",
    alert_ws_stop_title: "वर्कस्पेस टाइमर बंद करें",
    alert_ws_stop_message: "आपने 8 घंटे 5 मिनट+ लॉग किया है। टाइमर बंद करें और EOD भेजें।",
    eod_modal_title: "Teams पर अपडेट भेजें",
    eod_modal_label: "EOD",
    eod_modal_instruction: "अपने ग्रुप को भेजने के लिए संदेश चुनें:",
    eod_custom_toggle: "कस्टम संदेश लिखें...",
    eod_send_custom: "कस्टम संदेश भेजें",
    eod_custom_placeholder: "अपना संदेश यहाँ लिखें...",
    eod_suggested_prefix: "सुझाव:",
  },
};

let currentLanguage = "en";
let funnyTextMode = true;

function initLanguage() {
  chrome.storage.local.get(["language", "funnyTextMode"], (data) => {
    currentLanguage = data.language || "en";
    funnyTextMode = data.funnyTextMode !== false;
    applyLanguage();
  });
}

function setLanguage(lang) {
  if (translations[lang]) {
    currentLanguage = lang;
    chrome.storage.local.set({ language: lang });
    applyLanguage();
  }
}

function setFunnyTextMode(enabled) {
  funnyTextMode = enabled;
  chrome.storage.local.set({ funnyTextMode: enabled });
  applyLanguage();
}

function t(key) {
  const funnyKey = funnyTextMode ? `${key}_funny` : key;
  return (
    translations[currentLanguage][funnyKey] ||
    translations[currentLanguage][key] ||
    translations.en[funnyKey] ||
    translations.en[key] ||
    key
  );
}

function applyLanguage() {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    const translation = t(key);

    if (el.tagName === "INPUT" && el.type === "button") {
      el.value = translation;
    } else if (
      el.tagName === "INPUT" &&
      el.placeholder !== undefined &&
      el.hasAttribute("data-i18n-placeholder")
    ) {
      el.placeholder = t(el.getAttribute("data-i18n-placeholder"));
    } else {
      el.textContent = translation;
    }
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    el.placeholder = t(el.getAttribute("data-i18n-placeholder"));
  });
}
